booking/urls.py
from django.urls import path
from .views import IndexView, RideRequestView, RideDetailView, RideRequestAPI

# TODO: Add ur names/namespaces in the path
app_name = "booking"
urlpatterns = [
    path('', IndexView.as_view(), name='ride-index'),  # ride list view
    path('new/', RideRequestView.as_view(), name='ride-request'),  # Add this /about/ route
    # path('<int:ride_id>/', RideDetailView.as_view()),
    path('details/', RideDetailView.as_view(), name='ride-details'),
    path('api/ride-request/', RideRequestAPI.as_view(), name='ride-request-api')
]

home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
    path('', views.HomePageView.as_view(), name="index"),
    path('about/', views.AboutPageView.as_view(), name="about"),  # Add this /about/ route
]

taxibooking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('home.urls', namespace="home")),
    path('ride/', include('booking.urls', namespace="booking")),
]

api/models.py
from django.db import models

# Create your models here.

booking/models.py
# from django.db import models

# Create your models here.
from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute


class Ride(Model):
    """
    A DynamoDB Ride model
    """
    class Meta:
        table_name = "dynamodb-rides-local"
        host = "http://localhost:8500"
    ride_id = UnicodeAttribute(hash_key=True)
    time = UnicodeAttribute(range_key=True)
    status = UnicodeAttribute()

home/models.py
from django.db import models

# Create your models here.

booking/forms.py
from django import forms

class RideRequestForm(forms.Form):
    username = forms.CharField()
    origin = forms.CharField()
    destination = forms.CharField()
    time = forms.CharField()

api/views.py
from django.shortcuts import render

# Create your views here.

booking/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# Create your views here.
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import TemplateView
from django.views import View
from .forms import RideRequestForm
from .models import Ride
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect


# Create your views here.
class IndexView(TemplateView):
    # This view will return the rides index page
    # for now it will be a list of all rides, in a list view
    def get(self, request, **kwargs):
        return render(request, 'ride_index.html', context=None)


# create a view to fill a simple form and submit a ride request
class RideRequestView(TemplateView):
    def get(self, request):
        form = RideRequestForm()
        # print(form)
        return render(request, template_name='ride_request.html', context={'form': form})

    def post(self, request):
        form = RideRequestForm(data=request.POST)
        if form.is_valid():
            print("form is valid")
            import pdb;pdb.set_trace()
            ride_details = form.cleaned_data
            print(ride_details)
            # create ride_id from ride details and and write to dynamodb

        else:
            print("form is invalid")
            # form = RideRequestForm()
            # return redirect('booking:ride-request')
        # return redirect('booking:ride-details')
        return render(request, template_name='ride_request.html', context={'form': form})


# creates a detail view for a ride and reverses to a unique ride url generated from ride ID as parameter
class RideDetailView(View):
    # this shows the ride details and ride status
    # must generate ride id, and redirect to unique url made using the ride id
    def get(self, request, *args, **kwargs):
        # context = {'ride': ''}
        #fetch data from db
        return render(request, 'ride_details.html')

class RideRequestAPI(View):
    def get(self, request):
        data = {"status": "REQUESTED"}
        return JsonResponse(data)

    # def post(self, request):
    #     form = RideRequestForm(data=request.POST)
    #     if form.is_valid():
    #         print("form is valid")
    #         ride_details = form.cleaned_data
    #         print(ride_details)
    #         # create ride_id from ride details and and write to dynamodb

home/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class HomePageView(TemplateView):
    def get(self, request, **kwargs):
        return render(request, 'index.html', context=None)


# Single page view
class AboutPageView(TemplateView):
    template_name = "about.html"

booking/templates/ride_cancel.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Hola! Ride Cancel</title>
    </head>
    <body>
        <h1>Cancel Ride</h1>
        <p>
            Ride being cancelled by rider/driver.
            <a href="">Save to DynamoDB</a>
        </p>
    </body>
</html>

booking/templates/ride_details.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Hola! My Ride</title>
    </head>
    <body>
        <h1>My Ride</h1>
        <p>
            Ride has been <strong>Requested</strong>.
            <a href="">Save to DB</a>
            <a href="">Cancel Ride</a>
            <a href="">Reschedule Ride</a>

        </p>
        <a href="/">Go Home!</a>
    </body>
</html>

booking/templates/ride_index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Hola Cabs</title>
    </head>
    <body>
        <h1>My Rides</h1>
        <a href="/">Go Home!</a>
    </body>
</html>

booking/templates/ride_request.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Hola! Ride Request</title>
    </head>
    <body>
        <h1>Book a ride</h1>
        <p>Fill up the form below and click on the Request button</p>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Request</button>
        </form>
    <a href="/">Go Home!</a>
    </body>
</html>

home/templates/about.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Hola Cabs</title>
    </head>
    <body>
        <h1>Bahar Se Bhola</h1>
        <p>
            This project is for educational purposes only.
        </p>
        <a href="{% url 'home:index' %}">Go Home!</a>
    </body>
</html>

home/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Hola Cabs</title>
    </head>
    <body>
        <h1>Hola Cabs</h1>
        <p>
            Book a Ride
            <a href="{% url 'booking:ride-request' %}">Book</a>
            <a href="{% url 'booking:ride-request-api' %}">Book GET API</a>
        </p>
        <p>
            View Rides
            <a href="{% url 'booking:ride-index' %}">View</a>
        </p>
        <a href="{% url 'home:about' %}">About</a>
    </body>
</html>